---
- name: App Server Demos
  hosts: webserver

  tasks:
    - include_vars: ../defaults/main.yml

    - include_tasks: ../tasks/main.yml
      tags: [facts, netbox]

  handlers:
    - import_tasks: ../handlers/main.yml