---
- name: App Server Demos
  hosts: all
  gather_facts: false
  connection: local

  handlers:
    - import_tasks:
      file: ../handlers/main.yml

  tasks:
    - include_vars: ../defaults/main.yml

    - include_tasks: ../tasks/main.yml
      tags: [facts, netbox]

